[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions=[

{ access = "read", path = "./broadcast/DeployBridge.s.sol/" },
]

remappings=['@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts']

[rpc_endpoints]
eth_mainnet_sandbox = "${ETH_MAINNET_SANDBOX}" 
pol_mainnet_sandbox = "${POL_MAINNET_SANDBOX}" 